# Generated by Django 5.1.6 on 2025-03-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_customuser_alter_itemfound_user_alter_itemlost_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemlost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
    ]
