# Generated by Django 5.1.6 on 2025-03-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_chatmessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
