# Generated by Django 5.1.6 on 2025-03-30 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_delete_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemfound",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="itemfound",
            name="condition",
            field=models.CharField(
                choices=[("New", "New"), ("Used", "Used"), ("Damaged", "Damaged")],
                default="Used",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="itemfound",
            name="tags",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="itemlost",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="itemlost",
            name="condition",
            field=models.CharField(
                choices=[("New", "New"), ("Used", "Used"), ("Damaged", "Damaged")],
                default="Used",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="itemlost",
            name="tags",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="itemfound",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
        migrations.CreateModel(
            name="MatchingWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_weight", models.FloatField(default=0.5)),
                ("text_weight", models.FloatField(default=0.3)),
                ("location_weight", models.FloatField(default=0.2)),
                ("category_weight", models.FloatField(default=0.1)),
                ("time_decay_factor", models.FloatField(default=0.01)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user",)},
            },
        ),
    ]
