# Generated by Django 5.1.6 on 2025-04-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_remove_itemfound_image_remove_itemlost_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemfound",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
        migrations.AddField(
            model_name="itemlost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
        migrations.DeleteModel(
            name="ItemImage",
        ),
    ]
