# Generated by Django 5.1.6 on 2025-04-05 08:40

import django.db.models.deletion
import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_chatmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="sender",
            new_name="ender",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=mainapp.models.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=mainapp.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="item_found",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainapp.itemfound",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="item_lost",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainapp.itemlost",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
